- pkg/fetch/nvd/api/cve/cve.go
- pkg/fetch/nvd/api/cve/testdata/golden/1_item/2023/CVE-2023-47800.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_items/2023/CVE-2023-47488.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_items/2023/CVE-2023-47489.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_items/2023/CVE-2023-47613.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-36014.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-36024.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-39796.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-45167.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-46729.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-47246.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-47800.json
- pkg/fetch/nvd/api/cve/testdata/golden/3_pages/2023/CVE-2023-6069.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-36014.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-36024.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-39796.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-45167.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-46729.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-47246.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-47800.json
- pkg/fetch/nvd/api/cve/testdata/golden/increase/2023/CVE-2023-6069.json
- pkg/fetch/nvd/api/cve/types.go
Example is
before:
```
{
"cve": {                            ## <===== this level is eliminated
"id": "CVE-2023-47800",
"sourceIdentifier": "cve@mitre.org",
"vulnStatus": "Received",
"published": "2023-11-10T07:15:07.910",
"lastModified": "2023-11-10T07:15:07.910",
"descriptions": [
{
"lang": "en",
"value": "Natus NeuroWorks and SleepWorks before 8.4 GMA3 utilize a default password of xltek for the Microsoft SQL Server service sa account, allowing a threat actor to perform remote code execution, data exfiltration, or other nefarious actions such as tampering with data or destroying/disrupting MSSQL services."
}
],
"references": [
{
"source": "cve@mitre.org",
"url": "https://partner.natus.com/m/7cd3bcca88e446d4/original/NeuroWorks-SleepWorks-Product-Security-Bulletin.pdf"
},
{
"source": …
```
> Eliminate the unnecessary "cve" level in output json files

- pkg/fetch/jvn/feed/detail/detail.go
- pkg/fetch/jvn/feed/product/product.go
- pkg/fetch/jvn/feed/rss/rss.go
- pkg/fetch/jvn/feed/util/util.go
- pkg/fetch/jvn/feed/util/util_test.go
https://github.com/MaineK00n/vuls-data-update/actions/runs/7008939058/job/19066356264#step:8:40
> feat(fetch/jvn/feed): retry if unexpected EOF is encountered

- pkg/fetch/nvd/api/cpematch/cpematch.go
https://nvd.nist.gov/general/news/cpematch-resultsperpage-update
> feat(fetch/nvd/cpi/cpematch): change resultsPerPageMax from 5000 to 500

- pkg/cmd/fetch/fetch.go
- pkg/fetch/redhat/cve/cve.go
test run https://github.com/MaineK00n/vuls-data-update/actions/runs/10419207879/job/28856789433
> fix(ci/fetch/redhat/cve): change parameter for a little speedup

- pkg/fetch/ubuntu/oval/oval.go
- pkg/fetch/ubuntu/oval/testdata/golden/jammy/usn/variables/constant_variable/oval%3Acom.ubuntu.jammy%3Avar%3A518110000000.json
Add missing files of USN variables
> fix(fetch/ubuntu/oval): store USN variables

- .github/workflows/test.yml
- .gitmodules
- pkg/cmd/diff/diff.go
- pkg/cmd/root/root.go
- pkg/cmd/util/flag/choices.go
- pkg/diff/diff.go
- pkg/diff/diff_test.go
- pkg/diff/git.go
- pkg/diff/types.go
- pkg/diff/util/util.go
related repos for testing
- https://github.com/vulsio/vuls-data-extracted-diff-test/
- https://github.com/vulsio/vuls-data-extracted-diff-test-archive-1/
- https://github.com/vulsio/vuls-data-raw-diff-test/
> feat(cmd/diff): add diff command

- pkg/fetch/ubuntu/oval/oval.go
```console
$ go run cmd/vuls-data-update/main.go fetch ubuntu-oval
$ $ tree -L 3 ~/.cache/vuls-data-update/fetch/ubuntu/oval/
/home/mainek00n/.cache/vuls-data-update/fetch/ubuntu/oval/
├── bionic
│   ├── cve
│   │   ├── fips
│   │   ├── fips-updates
│   │   └── main
│   ├── pkg
│   │   ├── fips
│   │   ├── fips-updates
│   │   └── main
│   └── usn
│       ├── definitions
│       ├── objects
│       ├── states
│       ├── tests
│       └── variables
├── focal
│   ├── cve
│   │   ├── fips
│   │   ├── fips-updates
│   │   └── main
│   ├── pkg
│   │   ├── fips
│   │   ├── fips-updates
│   │   └── main
│   └── usn
│       ├── definitions
│       ├── objects
│       ├── states
│       ├── tests
│       └── variables
├── jammy
│   ├── cve
│   │   ├── bluefield
│   │   ├── fips-preview
│   │   …
```
> fix(fetch/ubuntu/oval): add services

- .github/workflows/extract-nightly.yml
- .github/workflows/extract.yml
https://github.com/vulsio/filter-vuls-data-extracted-redhat/pull/4
> feat(ci/extract*): update extract-redhat-rhel

- pkg/fetch/suse/cvrf_cve/cvrf_cve.go
https://github.com/vulsio/vuls-data-db/actions/runs/14073411674/job/39411963409#step:9:39
https://github.com/vulsio/vuls-data-db/actions/runs/14025192051/job/39262605127#step:9:39
> fix(fetch/suse/cvrf_cve): retry when unexpected EOF occurs

- pkg/fetch/nvd/api/cve/types.go
> feat(fetch/nvd/api/cve): add cveTags

- pkg/extract/redhat/vex/vex.go
https://security.access.redhat.com/data/csaf/v2/vex/2016/cve-2016-9840.json
https://github.com/vulsio/vuls-data-db/actions/runs/15549026295/job/43776973952#step:10:173
```console
$ go run cmd/vuls-data-update/main.go extract redhat-vex --dir ~/.cache/vuls-data-update/dotgit/vuls-data-extracted-redhat-vex ~/.cache/vuls-data-update/dotgit/vuls-data-raw-redhat-vex ~/.cache/vuls-data-update/dotgit/vuls-data-raw-redhat-repository-to-cpe
...
2025/06/10 15:13:47 [WARN] unexpected purl format. expected: "pkg:rpm/redhat/<name>?arch=<arch>", actual: "pkg:rpm/redhat/rsync"
...
```
> feat(extract/redhat/vex): skip unfixed package with no arch in PURL

- pkg/extract/oracle/oracle.go
https://github.com/vulsio/vuls-data-db/actions/runs/15600094174/job/43938438504#step:9:63
> fix(extract/oracle): support ELBA, ELEA prefix

- pkg/fetch/nvd/api/cpe/cpe.go
- pkg/fetch/nvd/api/cpematch/cpematch.go
- pkg/fetch/nvd/api/cve/cve.go
- pkg/fetch/nvd/api/util/export_test.go
- pkg/fetch/nvd/api/util/util.go
- pkg/fetch/nvd/api/util/util_test.go
> feat(fetch/nvd/api): add Backoff to interpret Retry-After 0 as 30s

- pkg/fetch/echo/echo_test.go
https://github.com/MaineK00n/vuls-data-update/actions/runs/15892563982/job/44817745776
> test(fetch/echo): sort package slices

- pkg/cmd/fetch/fetch.go
- pkg/fetch/siemens/csaf/csaf.go
- pkg/fetch/siemens/csaf/csaf_test.go
- pkg/fetch/siemens/csaf/testdata/fixtures/happy/ssa-426509.json
- pkg/fetch/siemens/csaf/testdata/fixtures/happy/ssa-feed-tlp-white.json
- pkg/fetch/siemens/csaf/testdata/golden/2024/SSA-426509.json
- pkg/fetch/siemens/csaf/types.go
> feat(fetch): add siemens-csaf

- pkg/cmd/fetch/fetch.go
- pkg/fetch/sick/csaf/csaf.go
- pkg/fetch/sick/csaf/csaf_test.go
- pkg/fetch/sick/csaf/testdata/fixtures/happy/csaf-feed-tlp-white.json
- pkg/fetch/sick/csaf/testdata/fixtures/happy/sca-2025-0007.json
- pkg/fetch/sick/csaf/testdata/golden/2025/SCA-2025-0007.json
- pkg/fetch/sick/csaf/types.go
> feat(fetch): add sick-csaf

- pkg/cmd/fetch/fetch.go
- pkg/fetch/rootio/rootio.go
- pkg/fetch/rootio/rootio_test.go
- pkg/fetch/rootio/testdata/fixtures/happy/cve_feed
- pkg/fetch/rootio/testdata/golden/alpine.json
- pkg/fetch/rootio/testdata/golden/debian.json
- pkg/fetch/rootio/types.go
> feat(fetch): add rootio

- pkg/extract/redhat/csaf/csaf.go
- pkg/extract/redhat/vex/testdata/fixtures/vex/2016/CVE-2016-7066.json
- pkg/extract/redhat/vex/testdata/golden/data/2016/CVE-2016-7066.json
- pkg/extract/redhat/vex/vex.go
https://github.com/vulsio/vuls-data-db/actions/runs/16184484710/job/45687420022#step:10:175
> fix(extract/redhat/csaf, vex): skip purl type

- pkg/cmd/fetch/fetch.go
- pkg/fetch/ubuntu/tracker/testdata/golden/1999/CVE-1999-1572.json
- pkg/fetch/ubuntu/tracker/testdata/golden/2005/CVE-2005-0406.json
- pkg/fetch/ubuntu/tracker/testdata/golden/2006/CVE-2006-0836.json
- pkg/fetch/ubuntu/tracker/testdata/golden/2022/CVE-2022-36879.json
- pkg/fetch/ubuntu/tracker/tracker.go
- pkg/fetch/ubuntu/tracker/types.go
> refactor!(fetch/ubuntu/tracker): update parser

- pkg/extract/oracle/oracle.go
https://github.com/vulsio/vuls-data-db/actions/runs/16498861592/job/46651556207#step:9:151
> fix(extract/oracle): skip some parsing errors

- pkg/extract/types/data/detection/condition/criteria/criterion/versioncriterion/package/package.go
- pkg/extract/types/data/detection/condition/criteria/criterion/versioncriterion/package/package_test.go
- pkg/extract/types/data/detection/condition/criteria/criterion/versioncriterion/package/source/source.go
- pkg/extract/types/data/detection/condition/criteria/criterion/versioncriterion/package/source/source_test.go
- pkg/extract/types/data/detection/condition/criteria/criterion/versioncriterion/versioncriterion.go
Reverts MaineK00n/vuls-data-update#498
> Revert "feat(.../vc/package/source): rename when kernel package"

- pkg/fetch/fedora/fedora.go
- pkg/fetch/fedora/fedora_test.go
- pkg/fetch/fedora/testdata/fixtures/kojihub/findBuildID/mysql-8.0-3820230907003352.75741a8b.xml
- pkg/fetch/fedora/testdata/fixtures/kojihub/getBuild/mysql-8.0-3820230907003352.75741a8b.xml
- pkg/fetch/fedora/testdata/golden/F38M/2023/FEDORA-MODULAR-2023-5b8a7bde59.json
- pkg/fetch/fedora/types.go
- pkg/fetch/fedora/xmlrpc/marshal_test.go
- pkg/fetch/fedora/xmlrpc/testdata/fixtures/getBuild.xml
- pkg/fetch/fedora/xmlrpc/unmarshal_test.go
sample response
```
$ curl -X POST --data "<?xml version='1.0'?><methodCall>\n<methodName>getBuild</methodName><params><param><value>mysql-8.0-3820230907003352.75741a8b</value></param></params></methodCall>" https://koji.fedoraproject.org/kojihub
```
modular release fetch test
```
$ vuls-data-update fetch fedora F28M F29M F30M F31M F32M F33M F34M F35M F36M F37M F38M
```
> feat(fetch/fedora): add module info

- pkg/cmd/dotgit/dotgit.go
- pkg/cmd/dotgit/registry.go
- pkg/dotgit/registry/delete/delete.go
- pkg/dotgit/registry/delete/delete_test.go
> feat(dotgit/registry): add delete cmd

- pkg/fetch/redhat/appstream-lifecycle/appstream-lifecycle.go
- pkg/fetch/redhat/appstream-lifecycle/appstream-lifecycle_test.go
- pkg/fetch/redhat/appstream-lifecycle/testdata/fixtures/rhel-retired-rolling-app-stream.html
- pkg/fetch/redhat/appstream-lifecycle/testdata/golden/Retired-Rolling-Application-Streams/8.json
- pkg/fetch/redhat/appstream-lifecycle/testdata/golden/Retired-Rolling-Application-Streams/9.json
- pkg/fetch/redhat/appstream-lifecycle/types.go
scraping https://access.redhat.com/support/policy/updates/rhel-app-retired-rolling-streams
> feat(fetch/redhat/appstream-lifecycle): add retired rolling
